# blueprints/get_intent_bp.py
# This file was auto-generated by Aura's create_new_tool blueprint.
from src.foundry.blueprints import Blueprint

# Parameters schema for the LLM. The executor will inject the project_context.
params = {
    "type": "object",
    "properties": {},
    "required": []
}

blueprint = Blueprint(
    id="get_intent",
    description="Reads the content of the 'intent.md' file from the project root and returns it as a string.",
    parameters=params,
    action_function_name="get_intent"
)